export const SPAN_METADATA = Symbol('DATADOG_SPAN_METADATA');
export const SPAN_METADATA_ACTIVE = Symbol('DATADOG_SPAN_METADATA_ACTIVE');
export const TRACE_INJECTORS = Symbol('DATADOG_TRACE_INJECTORS');
